<?php
if (!isset($autoPlay)) $autoPlay = 'yes';
?>
<!--Configuracion player david-->
<link rel="stylesheet" type="text/css"  href="content/global.css?v=<?=rand(100,999);?>"/>
    <script type="text/javascript" src="java/FWDUVPlayer.js"></script>
    
    <!-- Setup video player-->
<script type="text/javascript">
    FWDUVPUtils.onReady(function(){
 
        new FWDUVPlayer({       
             
        //main settings
				useYoutube:"no",
				useVimeo:"no",
				instanceName:"player1",
				parentId:"myDiv",
				playlistsId:"playlists",
				mainFolderPath:"content",
				skinPath:"minimal_skin_white",
				displayType:"responsive",
				fillEntireVideoScreen:"no",
				googleAnalyticsTrackingCode:"UA-118904852-1",
				useHEXColorsForSkin:"no",
				normalHEXButtonsColor:"#FF0000",
				selectedHEXButtonsColor:"#000000",
				useDeepLinking:"no",
				addKeyboardSupport:"yes",
				showPreloader:"yes",
				preloaderBackgroundColor:"#000000",
				preloaderFillColor:"#FFFFFF",
				autoScale:"yes",
				showButtonsToolTip:"yes", 
				stopVideoWhenPlayComplete:"no",
				showShareButton:"no",
				autoPlay:"<?=$autoPlay?>",
				loop:"yes",
				shuffle:"no",
				maxWidth:900,
				maxHeight:500,
				buttonsToolTipHideDelay:1.5,
				volume:.3,
				backgroundColor:"#000000",
				videoBackgroundColor:"#000000",
				posterBackgroundColor:"#0099FF",
				buttonsToolTipFontColor:"#5a5a5a",
				//logo settings
				showLogo:"no",
				hideLogoWithController:"yes",
				logoPosition:"topRight",
				logoMargins:5,
				//playlists/categories settings
				showPlaylistsSearchInput:"yes",
				showPlaylistsButtonAndPlaylists:"no",
				showPlaylistsByDefault:"no",
				thumbnailSelectedType:"opacity",
				startAtPlaylist:0,
				buttonsMargins:0,
				thumbnailMaxWidth:350, 
				thumbnailMaxHeight:350,
				horizontalSpaceBetweenThumbnails:40,
				verticalSpaceBetweenThumbnails:40,
				inputBackgroundColor:"#333333",
				inputColor:"#999999",
				//playlist settings
				showPlaylistButtonAndPlaylist:"no",
				playlistPosition:"right",
				showPlaylistByDefault:"yes",
				showPlaylistName:"yes",
				showSearchInput:"yes",
				showLoopButton:"yes",
				showShuffleButton:"yes",
				showNextAndPrevButtons:"yes",
				forceDisableDownloadButtonForFolder:"yes",
				addMouseWheelSupport:"yes",
				startAtRandomVideo:"no",
				folderVideoLabel:"VIDEO ",
				playlistRightWidth:310,
				playlistBottomHeight:380,
				startAtVideo:0,
				maxPlaylistItems:50,
				thumbnailWidth:70,
				thumbnailHeight:70,
				spaceBetweenControllerAndPlaylist:2,
				spaceBetweenThumbnails:2,
				scrollbarOffestWidth:8,
				scollbarSpeedSensitivity:.5,
				mainSelectorBackgroundSelectedColor:"#FFFFFF",
				mainSelectorTextNormalColor:"#FFFFFF",
				mainSelectorTextSelectedColor:"#000000",
				mainButtonBackgroundNormalColor:"#212021",
				mainButtonBackgroundSelectedColor:"#FFFFFF",
				mainButtonTextNormalColor:"#FFFFFF",
				mainButtonTextSelectedColor:"#000000",
				playlistBackgroundColor:"#000000",
				playlistNameColor:"#FFFFFF",
				thumbnailNormalBackgroundColor:"#1b1b1b",
				thumbnailHoverBackgroundColor:"#313131",
				thumbnailDisabledBackgroundColor:"#272727",
				searchInputBackgroundColor:"#000000",
				searchInputColor:"#999999",
				youtubeAndFolderVideoTitleColor:"#FFFFFF",
				youtubeOwnerColor:"#888888",
				youtubeDescriptionColor:"#888888",
				//controller settings
				showController:"yes",
				showControllerWhenVideoIsStopped:"yes",
				showNextAndPrevButtonsInController:"no",
				showPlaybackRateButton:"no",
				showVolumeButton:"yes",
				showTime:"yes",
				showQualityButton:"yes",
				showInfoButton:"yes",
				showDownloadButton:"no",
				showFacebookButton:"no",
				showEmbedButton:"no",
				showFullScreenButton:"yes",
				disableVideoScrubber:"no",
				showScrubberWhenControllerIsHidden:"no",
				showMainScrubberToolTipLabel:"no",
				showDefaultControllerForVimeo:"no",
				repeatBackground:"no",
				controllerHeight:37,
				controllerHideDelay:3,
				startSpaceBetweenButtons:7,
				spaceBetweenButtons:20,
				scrubbersOffsetWidth:2,
				mainScrubberOffestTop:14,
				timeOffsetLeftWidth:5,
				timeOffsetRightWidth:3,
				timeOffsetTop:0,
				volumeScrubberHeight:80,
				volumeScrubberOfsetHeight:12,
				timeColor:"#888888",
				youtubeQualityButtonNormalColor:"#888888",
				youtubeQualityButtonSelectedColor:"#FFFFFF",
				thumbnailDisabledBackgroundColor:"#272727",
				searchInputBackgroundColor:"#000000",
				//subtitle
				subtitlesOffLabel:"Subtitle off",
				//popup add windows
				showPopupAdsCloseButton:"yes",
				//embed window and info window
				embedAndInfoWindowCloseButtonMargins:0,
				borderColor:"#333333",
				mainLabelsColor:"#FFFFFF",
				secondaryLabelsColor:"#a1a1a1",
				shareAndEmbedTextColor:"#5a5a5a",
				inputBackgroundColor:"#000000",
				inputColor:"#FFFFFF",
				//ads
				openNewPageAtTheEndOfTheAds:"no",
				playAdsOnlyOnce:"no",
				adsButtonsPosition:"right",
				skipToVideoText:"You can skip to video in: ",
				skipToVideoButtonText:"Skip Ad",
				adsTextNormalColor:"#888888",
				adsTextSelectedColor:"#FFFFFF",
				adsBorderNormalColor:"#666666",
				adsBorderSelectedColor:"#FFFFFF",
				//context menu
				showScriptDeveloper:"no",
				contextMenuBackgroundColor:"#1f1f1f",
				contextMenuBorderColor:"#1f1f1f",
				contextMenuSpacerColor:"#333",
				contextMenuItemNormalColor:"#888888",
				contextMenuItemSelectedColor:"#FFFFFF",
				contextMenuItemDisabledColor:"#444"
        });
    });
</script>